Repository alibaba/spring-cloud-alibaba, pull requests merged in 2023-01, with the labels that each got.

#3050 remove duplicate dependencies
  spring-cloud-alibaba-examples/spring-cloud-bus-rocketmq-example/pom.xml
Labels: dependencies

#3047 [fix issue #3043] support comment in nacos json config
  spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/parser/NacosJsonPropertySourceLoader.java
  spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-config/src/test/java/com/alibaba/cloud/nacos/parser/NacosJsonPropertySourceLoaderTests.java
Labels: enhancement

#3045 Fix the bug on delete Label-routing rule
  spring-cloud-alibaba-docs/src/main/asciidoc-zh/governance.adoc
  spring-cloud-alibaba-docs/src/main/asciidoc-zh/pic/image-2022-11-22-11-15-25-187.png
  spring-cloud-alibaba-docs/src/main/asciidoc-zh/pic/image-2022-11-22-11-25-298.png
  spring-cloud-alibaba-docs/src/main/asciidoc-zh/pic/image-2022-11-22-14-40-234.png
  spring-cloud-alibaba-docs/src/main/asciidoc/pic/image-2022-11-22-11-15-25-187.png
  spring-cloud-alibaba-docs/src/main/asciidoc/pic/image-2022-11-22-11-25-298.png
  spring-cloud-alibaba-docs/src/main/asciidoc/pic/image-2022-11-22-14-40-234.png
  spring-cloud-alibaba-examples/governance-example/authentication-example/readme-zh.md
  spring-cloud-alibaba-examples/governance-example/authentication-example/readme.md
  spring-cloud-alibaba-examples/governance-example/label-routing-example/readme-zh.md
  spring-cloud-alibaba-examples/governance-example/label-routing-example/readme.md
  spring-cloud-alibaba-starters/spring-cloud-alibaba-governance/governance-core/spring-cloud-starter-alibaba-governance-labelrouting/src/main/java/com/alibaba/cloud/router/repository/RouteDataRepository.java
  spring-cloud-alibaba-starters/spring-cloud-alibaba-governance/governance-core/spring-cloud-starter-alibaba-governance-labelrouting/src/main/java/com/alibaba/cloud/router/ribbon/LabelRouteLBRule.java
Labels: bug

#3092 fix SecretKey leakage risk
  spring-cloud-alibaba-starters/spring-cloud-starter-stream-rocketmq/src/main/java/com/alibaba/cloud/stream/binder/rocketmq/utils/RocketMQUtils.java
Labels: waiting for sync

#3103 Remove sentinel useless annotation
  spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-sentinel/src/main/java/com/alibaba/cloud/sentinel/SentinelProperties.java
Labels: sentinel
