Repository alibaba/spring-cloud-alibaba, pull requests merged in 2024-05, with the labels that each got.

#3717 roadmap: update roadmap docs
  Roadmap-zh.md
Labels: kind/docs, kind/chore

#3708 fix: fix sentinel applicaiton not reigtry sentinel console bug
  spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-sentinel/src/main/java/com/alibaba/cloud/sentinel/custom/SentinelAutoConfiguration.java
  spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-sentinel/src/main/java/com/alibaba/cloud/sentinel/custom/context/SentinelApplicationContextInitializer.java
  spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-sentinel/src/main/java/com/alibaba/cloud/sentinel/endpoint/SentinelHealthIndicator.java
  spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-sentinel/src/main/resources/META-INF/spring.factories
Labels: area/sentinel

#3715 feat: update dashscope version to 2.14.0
  spring-cloud-alibaba-dependencies/pom.xml
Labels: area/ai

#3714 feat: Set the api-key by means of an environment variable.
  spring-cloud-alibaba-examples/spring-cloud-ai-example/README-en.md
  spring-cloud-alibaba-examples/spring-cloud-ai-example/README.md
  spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-ai/src/main/java/com/alibaba/cloud/ai/tongyi/TongYiAutoConfiguration.java
  spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-ai/src/main/java/com/alibaba/cloud/ai/tongyi/constants/TongYiConstants.java
Labels: area/ai

#3735 feat: add spring config metadata
  spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-ai/pom.xml
Labels: wait-for-feedback, area/ai

#3731 fix: fix llm client thread safety
  spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-ai/src/main/java/com/alibaba/cloud/ai/tongyi/TongYiAutoConfiguration.java
Labels: kind/bug, area/ai

#3732 new features: add distributed scheduling support.
  spring-cloud-alibaba-dependencies/pom.xml
  spring-cloud-alibaba-examples/pom.xml
  spring-cloud-alibaba-examples/spring-cloud-scheduling-example/README-en.md
  spring-cloud-alibaba-examples/spring-cloud-scheduling-example/README.md
  spring-cloud-alibaba-examples/spring-cloud-scheduling-example/images/idea-server-port.png
  spring-cloud-alibaba-examples/spring-cloud-scheduling-example/pom.xml
  spring-cloud-alibaba-examples/spring-cloud-scheduling-example/src/main/java/com/alibaba/cloud/examples/schedule/ScheduleApplication.java
  spring-cloud-alibaba-examples/spring-cloud-scheduling-example/src/main/java/com/alibaba/cloud/examples/schedule/job/SimpleJob.java
  spring-cloud-alibaba-examples/spring-cloud-scheduling-example/src/main/resources/application-schedulerx.yaml
  spring-cloud-alibaba-examples/spring-cloud-scheduling-example/src/main/resources/application-shedlock.yaml
  spring-cloud-alibaba-examples/spring-cloud-scheduling-example/src/main/resources/application.yaml
  spring-cloud-alibaba-starters/pom.xml
  spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-schedulerx/pom.xml
  spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-schedulerx/src/main/java/com/alibaba/cloud/scheduling/SchedulingConstants.java
  spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-schedulerx/src/main/java/com/alibaba/cloud/scheduling/schedulerx/JobProperty.java
  spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-schedulerx/src/main/java/com/alibaba/cloud/scheduling/schedulerx/SchedulerxAutoConfigure.java
  spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-schedulerx/src/main/java/com/alibaba/cloud/scheduling/schedulerx/SchedulerxConfigurations.java
  spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-schedulerx/src/main/java/com/alibaba/cloud/scheduling/schedulerx/SchedulerxProperties.java
  spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-schedulerx/src/main/java/com/alibaba/cloud/scheduling/schedulerx/constants/SchedulerxConstants.java
  spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-schedulerx/src/main/java/com/alibaba/cloud/scheduling/schedulerx/service/JobSyncService.java
  spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-schedulerx/src/main/java/com/alibaba/cloud/scheduling/schedulerx/service/ScheduledJobSyncConfigurer.java
  spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-schedulerx/src/main/java/com/alibaba/cloud/scheduling/schedulerx/util/CronExpression.java
  spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-schedulerx/src/main/java/com/alibaba/cloud/scheduling/shedlock/ShedLockAutoConfigure.java
  spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-schedulerx/src/main/resources/META-INF/spring.factories
  spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-schedulerx/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
  spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-schedulerx/src/main/resources/shedlock/schema/schema-mysql.sql
  spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-schedulerx/src/test/java/com/alibaba/cloud/scheduling/schedulerx/util/CronExpressionTest.java
Labels: kind/enhancement, area/scheduling
