Repository alibaba/spring-cloud-alibaba, pull requests merged in 2024-04, with the labels that each got.

#3669 example: add ai-example simple front pages and update ai-example code
  spring-cloud-alibaba-examples/spring-cloud-ai-example/README-en.md
  spring-cloud-alibaba-examples/spring-cloud-ai-example/README.md
  spring-cloud-alibaba-examples/spring-cloud-ai-example/images/sca-ai-example-front.gif
  spring-cloud-alibaba-examples/spring-cloud-ai-example/src/main/java/com/alibaba/cloud/ai/example/tongyi/controller/TongYiController.java
  spring-cloud-alibaba-examples/spring-cloud-ai-example/src/main/java/com/alibaba/cloud/ai/example/tongyi/service/TongYiService.java
  spring-cloud-alibaba-examples/spring-cloud-ai-example/src/main/java/com/alibaba/cloud/ai/example/tongyi/service/impl/TongYiServiceImpl.java
  spring-cloud-alibaba-examples/spring-cloud-ai-example/src/main/resources/static/index.html
  spring-cloud-alibaba-examples/spring-cloud-ai-example/src/main/resources/static/js/marked.min.js
Labels: area/example, area/ai

#3692 chore: delete more file & move pr tmpl to .github folder
  .github/PULL_REQUEST_TEMPLATE.md
  04-13-20-44-43.wav
  CODE_OF_CONDUCT.adoc
Labels: kind/chore

#3693 chore: add issue commands
  .github/labels.yml
  .github/workflows/issue-command.yml
Labels: area/ci

#3700 fix: Nacos snapshot config npe
  spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-config/src/main/java/com/alibaba/cloud/nacos/refresh/NacosSnapshotConfigManager.java
Labels: waiting for sync
